services:
  ingestion:
    container_name: ingestion_script
    build: .
    depends_on:
      - pg_taxi
  pg_taxi:
    container_name: "${DATABASE_CONTAINER_NAME}"
    image: "postgres:latest"
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - "${HOST_VOLUME_DIR}:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"