from pathlib import Path
from decouple import config

ROOT_DIRECTORY = Path(__file__).parent.absolute()
HOST_PORT = config("HOST_PORT")
HOST_VOLUME_DIR = config("HOST_VOLUME_DIR")
DATABASE_CONTAINER_NAME = config("DATABASE_CONTAINER_NAME")
CONTAINER_PORT = config("CONTAINER_PORT")
POSTGRES_USER = config("POSTGRES_USER")
POSTGRES_PASSWORD = config("POSTGRES_PASSWORD")
POSTGRES_DB = config("POSTGRES_DB")
POSTGRES_TABLE_NAME = config("POSTGRES_TABLE_NAME")
DATASET_PARQUET = config("DATASET_PARQUET")
